spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/miniflow
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
      hibernate.type.preferred_json_mapper: jackson

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8084

logging:
  level:
    org.springframework.web: INFO
    com.miniflow.config.tenant: DEBUG

kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: hms-appointments-service
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    properties:
      schema.registry.url: http://localhost:8081
      specific.avro.reader: false
    auto-offset-reset: earliest
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    properties:
      schema.registry.url: http://localhost:8081

# Multi-tenant configuration
tenants:
  default-tenant: default
  configs:
    default:
      url: jdbc:postgresql://localhost:5432/miniflow
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
    tenant1:
      url: jdbc:postgresql://localhost:5432/miniflow_tenant1
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
    tenant2:
      url: jdbc:postgresql://localhost:5432/miniflow_tenant2
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver

# Made with Bob
