apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniflow-db
  labels:
    app: miniflow-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miniflow-db
  template:
    metadata:
      labels:
        app: miniflow-db
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: miniflow
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: miniflow-secrets
              key: DB_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: miniflow-secrets
              key: DB_PASSWORD
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: miniflow-db
  labels:
    app: miniflow-db
spec:
  selector:
    app: miniflow-db
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  type: ClusterIP

# Made with Bob
