apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniflow
  labels:
    app: miniflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miniflow
  template:
    metadata:
      labels:
        app: miniflow
    spec:
      containers:
      - name: miniflow
        image: miniflow:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8084
        env:
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: miniflow-secrets
              key: DB_USERNAME
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: miniflow-secrets
              key: DB_PASSWORD
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        command:
        - java
        - -jar
        - app.jar
        - --spring.config.location=file:/app/config/application.yml
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
          requests:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8084
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8084
          initialDelaySeconds: 30
          periodSeconds: 5
      volumes:
      - name: config-volume
        configMap:
          name: miniflow-config

# Made with Bob
